/*
  # Study Planner Application Schema

  ## Overview
  Creates the complete database schema for an AI-powered study planner application
  that helps users organize their study schedules with intelligent task distribution.

  ## New Tables Created

  ### 1. `profiles`
  User profile information
  - `id` (uuid, primary key, references auth.users)
  - `full_name` (text) - User's full name
  - `profile_photo_url` (text, nullable) - URL to profile photo in storage
  - `created_at` (timestamptz) - Account creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 2. `study_plans`
  Main study plan configurations
  - `id` (uuid, primary key)
  - `user_id` (uuid, foreign key to profiles)
  - `title` (text) - Plan title/name
  - `exam_date` (date) - Target exam date
  - `daily_study_hours` (integer) - Hours available per day
  - `subjects` (jsonb) - Array of subject objects with name and difficulty
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)

  ### 3. `study_tasks`
  Individual daily study tasks generated by AI
  - `id` (uuid, primary key)
  - `study_plan_id` (uuid, foreign key to study_plans)
  - `subject` (text) - Subject name
  - `task_date` (date) - Scheduled date
  - `duration_minutes` (integer) - Task duration
  - `description` (text) - Task description
  - `priority` (text) - high, medium, or low
  - `completed` (boolean) - Completion status
  - `created_at` (timestamptz)

  ## Security
  - Enable Row Level Security (RLS) on all tables
  - Users can only access their own data
  - Policies restrict SELECT, INSERT, UPDATE, DELETE to authenticated users
  - Each policy checks that auth.uid() matches the user_id

  ## Important Notes
  - All tables use RLS for data isolation
  - Foreign key constraints ensure data integrity
  - Timestamps use timestamptz for timezone awareness
  - Default values set for common fields
*/

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  profile_photo_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Create study_plans table
CREATE TABLE IF NOT EXISTS study_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  exam_date date NOT NULL,
  daily_study_hours integer NOT NULL DEFAULT 4,
  subjects jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own study plans"
  ON study_plans FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own study plans"
  ON study_plans FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own study plans"
  ON study_plans FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own study plans"
  ON study_plans FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Create study_tasks table
CREATE TABLE IF NOT EXISTS study_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  study_plan_id uuid NOT NULL REFERENCES study_plans(id) ON DELETE CASCADE,
  subject text NOT NULL,
  task_date date NOT NULL,
  duration_minutes integer NOT NULL,
  description text NOT NULL,
  priority text NOT NULL DEFAULT 'medium',
  completed boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE study_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own study tasks"
  ON study_tasks FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM study_plans
      WHERE study_plans.id = study_tasks.study_plan_id
      AND study_plans.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own study tasks"
  ON study_tasks FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM study_plans
      WHERE study_plans.id = study_tasks.study_plan_id
      AND study_plans.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own study tasks"
  ON study_tasks FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM study_plans
      WHERE study_plans.id = study_tasks.study_plan_id
      AND study_plans.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM study_plans
      WHERE study_plans.id = study_tasks.study_plan_id
      AND study_plans.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete own study tasks"
  ON study_tasks FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM study_plans
      WHERE study_plans.id = study_tasks.study_plan_id
      AND study_plans.user_id = auth.uid()
    )
  );

-- Create storage bucket for profile photos
INSERT INTO storage.buckets (id, name, public)
VALUES ('profile-photos', 'profile-photos', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for profile photos
CREATE POLICY "Users can upload own profile photos"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'profile-photos' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Users can update own profile photos"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'profile-photos' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Anyone can view profile photos"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'profile-photos');